name: calculate
description: A new Flutter application.
publish_to: 'none'
version: 1.6.1+11

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.1.3
  shared_preferences: ^2.0.6
  package_info: ^2.0.2
  url_launcher: ^6.0.6
  webview_flutter: ^4.0.1
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_remote_config: ^3.0.9
  version: ^3.0.2
  app_review: ^2.1.1+1
  google_mobile_ads: ^2.3.0
  app_tracking_transparency: ^2.0.1
  adaptive_dialog: ^1.8.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/blobs.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#B4CEB3"
