name: calculate
description: A new Flutter application.
publish_to: 'none'
version: 1.10.0+17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.1.3
  shared_preferences: ^2.0.6
  package_info_plus: ^4.2.0
  url_launcher: ^6.0.6
  webview_flutter: ^4.0.1
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_remote_config: ^3.0.9
  version: ^3.0.2
  in_app_review: ^2.0.9
  google_mobile_ads: ^2.3.0
  app_tracking_transparency: ^2.0.1
  adaptive_dialog: ^1.9.0
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  flutter_sliding_tutorial: ^2.0.0+1
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/blobs.png
    - assets/app_icon.png
    - assets/app_icon_clear.svg
    - assets/loading.json

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"
